name: Run MLflow Experiment

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow

jobs:
  run-experiment:
    runs-on: ubuntu-latest  # Environment to run the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: conda.yaml  # Specify your conda environment file
          activate-environment: mlflow-env  # Name of your conda environment
          use-mamba: true  # Optional: speeds up package installation
      - name: Install MLflow
        run: |
          conda activate mlflow-env  # Activate the conda environment
          conda install mlflow -y  # Install MLflow in the activated environment

      - name: Run MLflow experiment
        env:
          MLFLOW_TRACKING_URI: http://4.255.46.89:5000  # Your MLflow tracking server URL
          MLFLOW_ARTIFACT_URI: wasbs://ctsmlstackstgbronze@ctsmlstackstg.blob.core.windows.net/
        run: |
          echo "Running MLflow experiment"
          mlflow run . --env-manager conda  # Run the MLflow experiment in the current directory
